### ISSUE TITLE
Mapping 0.8.1rc3

### ISSUE THREAD

**Issue by MaratIR** [Tracardi/tracardi-api#190]
When using mapping, if you select equal if does not exist, the parameter will not be assigned to the profile in the event, because the profile is created with a ready-made schema in which the field already exists in the profile with the value "null". If you select append, then the parameter from the event will be added to the profile every time, even if it already exists, as a result we will get an array like ['1','2','1','3']. That is, only Equal works correctly.

**Comment by MaratIR** [comment]
![image](https://github.com/Tracardi/tracardi-api/assets/61867280/625f5833-0902-4a40-ba0c-61b08222777d)

**Comment by atompie** [comment]
obsolite
